# Generated by Django 5.0.4 on 2024-05-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('main_tier', models.CharField(max_length=200)),
                ('sub_tier', models.CharField(max_length=200)),
                ('date_added', models.CharField(max_length=200)),
            ],
        ),
    ]
